//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSTOKTAKIP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Personel()
        {
            this.TBL_Satis = new HashSet<TBL_Satis>();
        }
    
        public int PersonelID { get; set; }
        public string PersonelAD { get; set; }
        public string PersonelSOYAD { get; set; }
        public Nullable<int> Departman { get; set; }
    
        public virtual TBL_Departman TBL_Departman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Satis> TBL_Satis { get; set; }
    }
}
