//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSTOKTAKIP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Musteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Musteri()
        {
            this.TBL_Satis = new HashSet<TBL_Satis>();
        }
    
        public int MusteriID { get; set; }
        public string MusteriAD { get; set; }
        public string MusteriSOYAD { get; set; }
        public string Sehir { get; set; }
        public Nullable<decimal> Bakiye { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Satis> TBL_Satis { get; set; }
    }
}
