//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSTOKTAKIP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Satis
    {
        public int SatisID { get; set; }
        public Nullable<int> Urun { get; set; }
        public Nullable<int> Personel { get; set; }
        public Nullable<int> Musteri { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual TBL_Musteri TBL_Musteri { get; set; }
        public virtual TBL_Personel TBL_Personel { get; set; }
        public virtual TBL_Urunler TBL_Urunler { get; set; }
    }
}
